- platform: broadlink
  mac: EC:0B:AE:3D:DB:A3
  switches:
    - name: subwoofer_ligar
      command_on: "JgBQAAABJZQSFBETEhMSFBETEhMSExITEjgSOBE4EzgRORE4EjkROBI4EhMRFBI4ETgTExE4ExMRFBE4EjgSExITEjgRFBI4EQAFIQABJksSAA0F"
      command_off: "JgBQAAABJZQSFBETEhMSFBETEhMSExITEjgSOBE4EzgRORE4EjkROBI4EhMRFBI4ETgTExE4ExMRFBE4EjgSExITEjgRFBI4EQAFIQABJksSAA0F"
    - name: subwoofer_bluetooth
      command_on: "JgBQAAABJpMTExISExITExISExISExMSEzcSOBM3EzcSOBM2FDcTNhM3FBETNxQ2ExEVERMSExEUEhM2FBEUEhM2EzcUNhQ2EwAFHgABKUkTAA0F"
      command_off: "JgBQAAABJpMTExISExITExISExISExMSEzcSOBM3EzcSOBM2FDcTNhM3FBETNxQ2ExEVERMSExEUEhM2FBEUEhM2EzcUNhQ2EwAFHgABKUkTAA0F"
    - name: subwoofer_fm
      command_on: "JgBQAAABJ5MTEhQRFBETEhMSFBETEhMSFDYTNxM2FDcTNhM3FDYUNhMSEzcTNhQ3ExEUERQSExEUNhQRFBETEhQ2EzcUNhM3EwAFHgABJ0sRAA0F"
      command_off: "JgBQAAABJ5MTEhQRFBETEhMSFBETEhMSFDYTNxM2FDcTNhM3FDYUNhMSEzcTNhQ3ExEUERQSExEUNhQRFBETEhQ2EzcUNhM3EwAFHgABJ0sRAA0F"
    - name: subwoofer_av
      command_on: "JgBYAAABJ5MTEhMSFBETEhMRFRETEhMRFDcTNhQ2FDYUNhM2FTYTNxM2FBEUEhMRFDcTERQ2FBEUERM3FDYTNxMSEzYUEhM2FAAFHgABJ0sSAAxWAAEoShIADQU="
      command_off: "JgBYAAABJ5MTEhMSFBETEhMRFRETEhMRFDcTNhQ2FDYUNhM2FTYTNxM2FBEUEhMRFDcTERQ2FBEUERM3FDYTNxMSEzYUEhM2FAAFHgABJ0sSAAxWAAEoShIADQU="
    - name: subwoofer_volume_mais
      command_on: "JgBQAAABJZURFBETEhQRFBETEhMSFBETEjgSOBE5EjgRORE4EjkROBIUETgRORITERQSFg8TERQROREUERMSORE4EjgSOBI4EQAFIAABJ0sSAA0F"
      command_off: "JgBQAAABJZURFBETEhQRFBETEhMSFBETEjgSOBE5EjgRORE4EjkROBIUETgRORITERQSFg8TERQROREUERMSORE4EjgSOBI4EQAFIAABJ0sSAA0F"
    - name: subwoofer_volume_menos
      command_on: "JgBQAAABJZQSExMSExISExITExISExITEzcSOBI3EzgSNxI4EzcSOBITEjgSNxMTEjcTEhMTEhITNxMSExISOBMSEjgTNxI4EgAFHwABKEoSAA0F"
      command_off: "JgBQAAABJZQSExMSExISExITExISExITEzcSOBI3EzgSNxI4EzcSOBITEjgSNxMTEjcTEhMTEhITNxMSExISOBMSEjgTNxI4EgAFHwABKEoSAA0F"
    - name: subwoofer_mute
      command_on: "JgBYAAABJpQSExITEhMRFBEUEhMRFBEUEjgSOBE4EzgSOBE4EzgSNxI4EhMTExE4EjgSExIUERMSExI4EjgTEhMSETkSOBI4EgAFIAABJ0wSAAxYAAEnSxEADQU="
      command_off: "JgBYAAABJpQSExITEhMRFBEUEhMRFBEUEjgSOBE4EzgSOBE4EzgSNxI4EhMTExE4EjgSExIUERMSExI4EjgTEhMSETkSOBI4EgAFIAABJ0wSAAxYAAEnSxEADQU="